# Generated by Django 5.2.16 on 2026-07-13 13:47

import django.db.models.deletion
import django.utils.timezone
import documents.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_name", models.CharField(max_length=160)),
                ("student_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("sharecode", "Share code"),
                            ("proof_of_address", "Proof of address"),
                            ("cv", "CV"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("other_document_name", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("action", "Action required"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "Not sent"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_sent",
                        max_length=20,
                    ),
                ),
                ("email_error_code", models.CharField(blank=True, max_length=120)),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                (
                    "token_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=documents.storage.PrivateUploadStorage(),
                        upload_to=documents.storage.private_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=220)),
                ("detected_mime", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded_ip_hash", models.CharField(blank=True, max_length=64)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("request_created", "Request created"),
                            ("request_email_sent", "Request email sent"),
                            ("request_email_failed", "Request email failed"),
                            ("request_resent", "Request resent"),
                            ("document_uploaded", "Document uploaded"),
                            ("confirmation_email_sent", "Confirmation email sent"),
                            ("confirmation_email_failed", "Confirmation email failed"),
                            ("document_downloaded", "Document downloaded"),
                            ("request_completed", "Request completed"),
                            ("request_cancelled", "Request cancelled"),
                            ("request_expired", "Request expired"),
                            ("portal_login", "Portal login"),
                            ("portal_login_failed", "Portal login failed"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_portal_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="documents.documentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(
                fields=["status", "-created_at"], name="docs_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentrequest",
            index=models.Index(fields=["student_name"], name="docs_student_name_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event", "-created_at"], name="docs_audit_event_idx"
            ),
        ),
    ]
