# Generated by Django 5.2.16 on 2026-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("request_created", "Request created"),
                    ("request_email_sent", "Request email sent"),
                    ("request_email_failed", "Request email failed"),
                    ("request_resent", "Request resent"),
                    ("document_uploaded", "Document uploaded"),
                    ("confirmation_email_sent", "Confirmation email sent"),
                    ("confirmation_email_failed", "Confirmation email failed"),
                    ("document_downloaded", "Document downloaded"),
                    ("document_purged", "Document purged"),
                    ("request_completed", "Request completed"),
                    ("request_cancelled", "Request cancelled"),
                    ("request_expired", "Request expired"),
                    ("portal_login", "Portal login"),
                    ("portal_login_failed", "Portal login failed"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
